// Code generated by MockGen. DO NOT EDIT.
// Source: repository/balance_interface.go

// Package mock_repository is a generated GoMock package.
package repository

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/saskamegaprogrammist/userBalanceService/models"
	reflect "reflect"
)

// MockBalanceRepoI is a mock of BalanceRepoI interface
type MockBalanceRepoI struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceRepoIMockRecorder
}

// MockBalanceRepoIMockRecorder is the mock recorder for MockBalanceRepoI
type MockBalanceRepoIMockRecorder struct {
	mock *MockBalanceRepoI
}

// NewMockBalanceRepoI creates a new mock instance
func NewMockBalanceRepoI(ctrl *gomock.Controller) *MockBalanceRepoI {
	mock := &MockBalanceRepoI{ctrl: ctrl}
	mock.recorder = &MockBalanceRepoIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBalanceRepoI) EXPECT() *MockBalanceRepoIMockRecorder {
	return m.recorder
}

// GetBalanceByUserId mocks base method
func (m *MockBalanceRepoI) GetBalanceByUserId(user *models.Balance) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByUserId", user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByUserId indicates an expected call of GetBalanceByUserId
func (mr *MockBalanceRepoIMockRecorder) GetBalanceByUserId(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByUserId", reflect.TypeOf((*MockBalanceRepoI)(nil).GetBalanceByUserId), user)
}

// InsertUser mocks base method
func (m *MockBalanceRepoI) InsertUser(balance *models.Balance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUser indicates an expected call of InsertUser
func (mr *MockBalanceRepoIMockRecorder) InsertUser(balance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockBalanceRepoI)(nil).InsertUser), balance)
}
